name: Setup Runtime
description: Prepare Runtime in GitHub Actions

inputs:
  bun-version:
    description: Version of Bun to use
    default: latest # TODO(cedric): replace with fixed major version after fixing https://github.com/oven-sh/setup-bun/issues/37

  node-version:
    description: Version of Node to use
    default: 20.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Bun
      if: ${{ runner.os != 'Windows' }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
