---
name: Expo GitHub Action - Preview comment
author: Cedric van Putten <me@bycedric.com>
description: Preview Expo projects in pull requests
branding:
  icon: terminal
  color: gray-dark
runs:
  using: node16
  main: ../build/comment/index.js
inputs:
  project:
    description: Path to the Expo project, relative from the workspace
    required: false
  channel:
    description: Release channel to preview
    required: false
  message:
    description: Pull request comment template
    required: false
  message-id:
    description: A unique identifier to prevent multiple comments on the same pull request
    required: false
