---
name: Expo GitHub Action
author: Expo
description: Publish, build or manage your Expo app with GitHub Actions
branding:
  icon: terminal
  color: gray-dark
runs:
  using: node16
  main: build/setup/index.js
inputs:
  expo-version:
    description: Expo CLI version to install
  expo-cache:
    description: If Expo CLI should be cached to speed up installation
    default: true
  eas-version:
    description: EAS CLI version to install
  eas-cache:
    description: If EAS CLI should be cached to speed up installation
    default: true
  packager:
    description: The package manager used to install the CLIs
    default: yarn
  patch-watchers:
    description: If the action should patch the ENOSPC errors
    default: true
  token:
    description: Your Expo token, for authentication. (use with secrets)
  # Below are deprecated and won't be supported anymore
  eas-cache-key:
    description: A custom remote cache key to use for EAS CLI.
    deprecationMessage: Custom cache keys are deprecated and not used anymore.
  expo-cache-key:
    description: A custom remote cache key to use for Expo CLI.
    deprecationMessage: Custom cache keys are deprecated and not used anymore.
  username:
    description: Your Expo username, for authentication.
    deprecationMessage: Username/password authentication is deprecated, use a token instead.
  password:
    description: Your Expo password, for authentication. (use with secrets)
    deprecationMessage: Username/password authentication is deprecated, use a token instead.
