FROM bycedric/ci-expo

LABEL com.github.actions.name="Expo CLI Login"
LABEL com.github.actions.description="Use Expo CLI in your GitHub Actions workflow."
LABEL com.github.actions.icon="terminal"
LABEL com.github.actions.color="gray-dark"

ENTRYPOINT expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD