FROM bycedric/ci-expo:2

LABEL com.github.actions.name="Build web"
LABEL com.github.actions.description="Create a bundle for web deployments from your GitHub Actions workflow."
LABEL com.github.actions.icon="package"
LABEL com.github.actions.color="gray-dark"

ENTRYPOINT ["/entrypoint.sh", "build:web"]
