FROM bycedric/ci-expo:2

LABEL com.github.actions.name="Expo CLI"
LABEL com.github.actions.description="Use Expo CLI in your GitHub Actions workflow."
LABEL com.github.actions.icon="terminal"
LABEL com.github.actions.color="gray-dark"
