FROM bycedric/ci-expo:2

LABEL com.github.actions.name="Build Android"
LABEL com.github.actions.description="Create a standalone Android app in your GitHub Actions workflow."
LABEL com.github.actions.icon="package"
LABEL com.github.actions.color="gray-dark"

ENTRYPOINT ["/entrypoint.sh", "build:android"]
