FROM bycedric/ci-expo:2

LABEL com.github.actions.name="Build Expo iOS app (unofficial)"
LABEL com.github.actions.description="Create a standalone iOS app in your GitHub Actions workflow."
LABEL com.github.actions.icon="package"
LABEL com.github.actions.color="gray-dark"

ENTRYPOINT ["/entrypoint.sh", "build:ios"]
